### PR TITLE
Add a github action to get automated changelogs

### LINKED ISSUE #226: Upon PR merge, CI could add PR name to next Release draft
It's not unmanageable manually, but I wish the release draft was pre-filled with PR names. It's probably a 2-liner python script but I foresee travis being a pain.

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #226 

### Successful PR Checklist:
- [x] Create the PR labels
- [ ] Tests
  - [x] (not applicable?)
- [x] Documentation < Contibuting doc needs a words about this.
  - [ ] (not applicable?)
- [x] Had a good time contributing?

### CODE REVIEW

**Comment by elemoine** [comment]
I see that a 0.10.0 draft release was created, although none of the PRs associated with that release have the `PR:minor` label. So I am wondering why 0.9.1 was not picked as the next release version.

I'm also wondering what would happen if there was a 0.10.0 draft release and we actually pushed a 0.9.1 tag. I admit that this question is not related to Release Drafter.

**Comment by ewjoachim** [comment]
I've already changed the label names, but I'm still waiting for a review on https://github.com/peopledoc/procrastinate/pull/243 so that's why drafter is kinda all over the place.

Also, it is instructed to issue a minor release by default https://github.com/peopledoc/procrastinate/blob/8e05f4746018003d187991175207180b5c9a8058/.github/release-drafter.yml#L14

**Comment by ewjoachim** [comment]
> I'm also wondering what would happen if there was a 0.10.0 draft release and we actually pushed a 0.9.1 tag. I admit that this question is not related to Release Drafter.

Didn't understand your question, sorry...

**Comment by elemoine** [comment]
> Didn't understand your question, sorry...

It was a stupid question :-)

Let's say we have a 0.10.0 draft release, created by Release Drafter. And we change our mind, and decide to release 0.9.1 instead of 0.10.0. So we create a 0.9.1 tag and push it. I guess this is going to create a new Release in GitHub, named 0.9.1. So I guess it will be a manual process to copy the content of the 0.10.0 draft release to the 0.9.1 release, and remove the 0.10.0.

**Comment by elemoine** [comment]
> Also, it is instructed to issue a minor release by default

I had missed that. I though it was patch/incremental by default. Thanks.

**Comment by ewjoachim** [comment]
> Let's say [...]

I know you had your answer since, but to have it written somewhere: no, it's GitHub who does the tag when we publish the release, so now it's all done at the same place.

I'll clarify this part in the contributing doc.

**Pull request merged**
