### PR TITLE
Fix black version

### LINKED ISSUE #304: Do not use black>=20.8b0 for the moment
The last versions of black, `20.8b0` and `20.8b1` contain a bug that breaks our linting. See https://github.com/psf/black/issues/1649. We need to use the most recent version BELOW 20.8b0 for the moment.

### PR DESCRIPTION
**Pull request by thomasperrot**
Closes #304 

### Successful PR Checklist:

- [ ] Tests
  - [X] (not applicable?)
- [ ] Documentation
  - [X] (not applicable?)
- [X] Had a good time contributing?
- [ ] (Maintainers: add PR labels)

### CODE REVIEW

**Review by ewjoachim — COMMENTED** [review]
I’m ok temporarily excluding a release, I’d rather avoid pinning because this could stay in place longer than necessary.

If this is not a bug but Black’s formatting rules, what would be needed to fix our codebase ?

**Review by ewjoachim — CHANGES_REQUESTED** [review]
(see above)

**Comment by elemoine** [comment]
My initial plan was to use `black!=20.8b1`.

There's more information in this Black issue: https://github.com/psf/black/issues/1649. The comment https://github.com/psf/black/issues/1649#issuecomment-683327600 suggests to remove the trailing comas, which might indeed be a good option for us.

**Comment by ewjoachim** [comment]
Are you ok to close in favor of #306 ?

**Comment by ewjoachim** [comment]
Hm, I've been a little fast and I've merged already but feel free to continue the discussion if anything feels unresolved :)

**Pull request closed without merging**
