### PR TITLE
Fix postgres docker example in quickstart doc

### PR DESCRIPTION
**Pull request by tmartinfr**
### Successful PR Checklist:

- [ ] Tests
  - [ ] (not applicable?)
- [ ] Documentation
  - [ ] (not applicable?)
- [ ] Had a good time contributing?

### CODE REVIEW

**Comment by elemoine** [comment]
Hi @tmartinfr. To use what's recommended by the Postgres image's authors, we can use `-e POSTGRES_PASSWORD=password` on the `docker run` command line, and `password=password` in the arguments passed to `PostgresConnector`. If you agree with that, can you please make the changes to your branch?

**Comment by tmartinfr** [comment]
@elemoine I made a deliberate choice of using `POSTGRES_HOST_AUTH_METHOD=trust` to keep the later examples simpler, but I see no problem to change if you prefer. I will update the branch.

**Comment by tmartinfr** [comment]
@elemoine Done, don't know if you want to enforce 80-characters line in the doc ?

**Comment by ewjoachim** [comment]
@tmartinfr doc8 was happy in the build, and so are we :)
```
- doc8.checks.CheckMaxLineLength = 0
```
https://travis-ci.org/github/peopledoc/procrastinate/jobs/694151477#L387

BTW, the limit is 88 chars everywhere.

**Comment by elemoine** [comment]
I also prefer the "password" option because this is the one we use for the development environment (documented in the CONTRIBUTING doc).

**Pull request merged**
