### PR TITLE
Rename PostgresConnector into AiopgConnector

### LINKED ISSUE #186: Rename PostgresConnector to AiopgConnector
This issue suggests renaming PostgresConnector to AiopgConnector, for a more explicit class name. And we may want to add Psycopg2Connector or AsyncpgConnector in the future.

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #186 

Purely automated PR using search and replace.

Hopefully, no typo in the replacement :D

### Successful PR Checklist:

- [x] Tests
  - [ ] (not applicable?)
- [x] Documentation
  - [ ] (not applicable?)
- [x] Had a good time contributing?

### CODE REVIEW

**Comment by ewjoachim** [comment]
Yep, that's exactly what we thought.

The plan is currently to go to 1.0 and start advertizing this summer, so we're rushing all the breaking changes before. So read the [changelog](https://github.com/peopledoc/procrastinate/releases) which has a "Breaking changes" section :D

**Comment by elemoine** [comment]
I would have liked to merge #224 and cut a release before merging this, but I should have mentioned it before :-)

**Comment by ewjoachim** [comment]
Ah. We can still revert, it's ok. Or make a branch.

**Comment by ewjoachim** [comment]
@elemoine So what do you prefer we do ?

**Comment by elemoine** [comment]
I think it's ok to have the renaming in the next release.

**Pull request merged**
