### PR TITLE
Make the shell fixture properly terminate the shell process

### LINKED ISSUE #346: Warnings when executing the test_shell acceptance tests
I get warnings when executing the test_shell acceptance tests:

```
$ pytest tests/acceptance/test_shell.py                                                                                          
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.6, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/elemoine/.virtualenvs/procrastinate/bin/python                                                                  
cachedir: .pytest_cache                                                                                                                                                                        
django: settings: tests.acceptance.django_settings (from ini)                                                                                                                                  
rootdir: /home/elemoine/src/procrastinate, configfile: setup.cfg                                                                                                                               
plugins: mock-3.3.1, asyncio-0.14.0, cov-2.10.1, django-3.9.0, click-0.3                                                                                                                       
collected 1 item                                                                                                                                                                               
                                                                                                                                                                                               
tests/acceptance/test_shell.py::test_shell PASSED                                                                                                                                       [100%]E
xception ignored in: <function Popen.__del__ at 0x7fac6ebfe040>                                                                                                                                
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/lib/python3.8/subprocess.py", line 942, in __del__                                                                                                                                
    _warn("subprocess %s is still running" % self.pid,                                                                                                                                         
ResourceWarning: subprocess 1294352 is still running                                                                                                                                           
Exception ignored in: <_io.FileIO name=16 mode='rb' closefd=True>                                                                                                                              
Traceback (most recent call last):                                                                                                                                                             
  File "/home/elemoine/.virtualenvs/procrastinate/lib/python3.8/site-packages/_pytest/runner.py", line 123, in runtestprotocol                                                                 
    item.funcargs = None  # type: ignore[attr-defined]                                                                                                                                         
ResourceWarning: unclosed file <_io.TextIOWrapper name=16 encoding='utf-8'>                                                                                                                    
Exception ignored in: <_io.FileIO name=18 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/elemoine/.virtualenvs/procrastinate/lib/python3.8/site-packages/_pytest/runner.py", line 123, in runtestprotocol
    item.funcargs = None  # type: ignore[attr-defined]
ResourceWarning: unclosed file <_io.TextIOWrapper name=18 encoding='utf-8'>
```

### PR DESCRIPTION
**Pull request by elemoine**
Closes #346 

### Successful PR Checklist:

- [ ] Tests
  - [x] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)
- [x] Had a good time contributing?

### CODE REVIEW

**Comment by elemoine** [comment]
This is the build failure with Python 3.6:

```
=================================== FAILURES ===================================
___________________________________ test_cli ___________________________________

entrypoint = <function entrypoint.<locals>.ep at 0x7fcf7ecb98c8>

    def test_cli(entrypoint):
        result = entrypoint()
>       assert result.output.startswith("Usage:")
E       AssertionError: assert False
E        +  where False = <built-in method startswith of str object at 0x560937e2a330>('Usage:')
E        +    where <built-in method startswith of str object at 0x560937e2a330> = 'Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=False debug...  Administration shell for procrastinate.\n  worker        Launch a worker, listening on the given queues (or all...\n'.startswith
E        +      where 'Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=False debug...  Administration shell for procrastinate.\n  worker        Launch a worker, listening on the given queues (or all...\n' = <Result okay>.output

tests/integration/test_cli.py:22: AssertionError
```

My suspicion is that it's related to the exception filter we added with https://github.com/peopledoc/procrastinate/pull/338.

**Comment by elemoine** [comment]
@ewjoachim I confirm that the build passes with the filterwarnings configuration removed.

**Comment by ewjoachim** [comment]
and does it pass with you fix, without removing the filters ?

**Comment by elemoine** [comment]
The error messages:

```
----------------------------- Captured stdout call -----------------------------
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=False debug=False>>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/asyncio/base_events.py", line 531, in __del__
    source=self)
ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
Exception ignored in: <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=2049, proto=0>
ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=2049, proto=0>
Exception ignored in: <socket.socket fd=11, family=AddressFamily.AF_UNIX, type=2049, proto=0>
ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_UNIX, type=2049, proto=0>
Usage: cli [OPTIONS] COMMAND [ARGS]...
```

**Review by ewjoachim — APPROVED** [review]

**Pull request merged**
